import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { LanguageProvider } from '@/context/Languagecontext';
import { ThemeContext } from '@/context/ThemeContext';
import { ThemeProvider } from '@/context/ThemeContext';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html className="dark">
            <body className="bg-soft-gradient min-h-screen w-full px-5 text-black dark:bg-gray-900 dark:text-white">
                <ThemeProvider>
                    <LanguageProvider>
                        <Header />
                        <div
                            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center justify-center pt-[60px]`}
                        >
                            {children}
                        </div>
                        <Footer />
                    </LanguageProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
